baseURL: "https://ashutoshsingh1093.netlify.app"
languageCode: en-us
title: Ashutosh Singh
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: About
      name: About
      url: /About
      weight: 15
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Experience
      url: /experience
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60


params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Ashutosh Singh"
    subtitle: "A data enthusiast with a passion for using data to solve real-world problems. I graduated from **Northeastern University, Boston** with a **Master of Science in Applied Machine Intelligence**. I have six years of professional experience working in the **finance**, **healthcare**, and **insurance** sectors as a **Business Data Analyst** at **Xerox Business Services** and **Senior Analytics Consultant** at **NTT DATA**. I am proficient in diverse data science techniques and am passionate about utilizing my skills for a positive impact. I derive fulfillment from volunteering for environmental issues and promoting individual welfare. Additionally, I enjoy sports and reading about pharmaceuticals, health, and finance."
    imageUrl: "home/SAS.jpg"
    imageWidth: 350
    imageHeight: 350  
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1p-44gaIX5W9qSHQafHq0RsnAgY9z-fEY/view?usp=sharing"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:singh.ashut@northeastern.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ashutoshkumarsingh1009/"  
    - name: "github"
      url: "https://github.com/Abhiashu10"
    - name: "kaggle"
      url: "https://www.kaggle.com/ashutoshsingh1093"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
