baseURL: "https://ashutoshsingh1093.netlify.app"
languageCode: en-us
title: Ashutosh Singh
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: About
      name: About
      url: /about
      weight: 17
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: experience
      name: Professional Experience
      url: /experience
      weight: 30
    - identifier: blog
      name: Blog
      url: /blog
      weight: 40
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60


params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Ashutosh Singh"
    subtitle: "A data enthusiast with a passion for using data to solve real-world problems. I graduated from **Northeastern University, Boston** with a **Master of Science in Applied Machine Intelligence**. With **6 years** of Professional experience as an **Analytics Consultant** at **NTT DATA** and **Business Data Analyst** at **Xerox Services**, I bring valuable industry knowledge. A **Lean Six Sigma certified** professional who integrates their expertise in **finance**, **healthcare**, & **insurance** with **data science** to communicate insights through data-driven narratives. I'm passionate about **Artificial Intelligence**, **Cloud** & **Business Analytics**. I also find fulfillment in volunteering for environmental causes & promoting individual welfare."
    imageUrl: "home/SAS.jpg"
    imageWidth: 300
    imageHeight: 300 
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/14fcXisX4s5rB5IBiJOcOdMUg963cjAxT/view?usp=share_link"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:singh.ashut@northeastern.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/ashutoshkumarsingh1009/"  
    - name: "github"
      url: "https://github.com/Abhiashu10"
    - name: "kaggle"
      url: "https://www.kaggle.com/ashutoshsingh1093"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
